project_name: xq
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    hooks:
      post: upx --best --lzma "{{ .Path }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '^TECH'
