project_name: xq
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goamd64:
      - ''
    hooks:
      post:
        - cmd: scripts/build-hook.sh
          env:
            - HOOK_TARGET={{ .Target }}
            - HOOK_PATH={{ .Path }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '^TECH'
