name: xq
base: core22
version: '1.1.0'
summary: Command-line XML and HTML beautifier and content extractor
description: |
  Command-line XML and HTML beautifier and content extractor.
  
  Usage:
    xq <file.xml>

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  xq:
    source: https://github.com/sibprogrammer/xq
    source-type: git
    plugin: go
    build-snaps:
      - go
